name: "Terraform apply on main-branch push"
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform fmt, init and apply"
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.4.5

    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: "Terraform setup"
        uses: hashicorp/setup-terraform@main
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: "Terraform fmt"
        id: fmt
        run: terraform fmt

      - name: "Terraform init"
        id: init
        run: terraform init

      - name: "Terraform apply"
        id: apply
        run: terraform apply
